### ISSUE TITLE
Svelte:Window auto-generated error

### ISSUE THREAD

**Issue by ArcBugRep** [IzK-ArcOS/ArcOS-Frontend#84]
File: https://web.izk-arcos.nl/assets/index-71f3a5c9.js (16599:15)

Uncaught TypeError: input.startsWith is not a function

TypeError: input.startsWith is not a function
    at CL.isValid (https://web.izk-arcos.nl/assets/index-71f3a5c9.js:16599:15)
    at CL.evaluate (https://web.izk-arcos.nl/assets/index-71f3a5c9.js:16584:26)
    at CL.__publicField.%%E (https://web.izk-arcos.nl/assets/index-71f3a5c9.js:16555:31)

> References br$21336-419766-185767-37436

**Comment by IzKuipers** [comment]
Related to: Calculator App
